"""Setup script for PetShop Amigo Fiel project.

Creates the full project with deep agents, skills, tools, and documents
via the Axolotl API.

Usage:
  # Via Docker (dentro do container):
  docker compose exec backend python scripts/setup_petshop.py

  # Local (com backend rodando):
  uv run python scripts/setup_petshop.py

  # Custom URL:
  AXOLOTL_API_URL=http://backend:8000/api/v1 python scripts/setup_petshop.py

Requires the backend to be running at BASE_URL (default: http://localhost:8000).
"""

import os
import sys
from pathlib import Path

import httpx

BASE_URL = os.environ.get("AXOLOTL_API_URL", "http://localhost:8000/api/v1")
DATA_DIR = Path(__file__).parent / "data"

client = httpx.Client(base_url=BASE_URL, timeout=30)


def create_project() -> str:
    """Create the PetShop project with deep_agent orchestration mode."""
    resp = client.post(
        "/projects",
        json={
            "name": "PetShop Amigo Fiel",
            "description": "Atendimento automatizado para petshop via chat/WhatsApp",
            "orchestration_mode": "deep_agent",
            "model": "openai:gpt-4.1-mini",
            "planner_prompt": (
                "Voce e a recepcionista virtual do PetShop Amigo Fiel, "
                "um petshop localizado em Sao Paulo.\n\n"
                "## Sua Personalidade\n"
                "- Simpatica, acolhedora e apaixonada por animais\n"
                "- Use linguagem informal mas profissional\n"
                "- Chame o cliente pelo nome quando souber\n"
                "- Use emojis com moderacao\n"
                "- Sempre pergunte o nome do pet\n\n"
                "## Regras de Negocio\n"
                "- Horario: Seg-Sab, 8h-19h. Domingo fechado.\n"
                "- Endereco: Rua das Flores, 123 - Vila Madalena, SP\n"
                "- WhatsApp: (11) 99999-0000\n"
                "- Pagamento: PIX, cartao (credito/debito), dinheiro\n\n"
                "## Fluxo de Atendimento\n"
                "1. Cumprimente o cliente e pergunte como pode ajudar\n"
                "2. Identifique a necessidade\n"
                "3. Delegue para o sub-agente especializado:\n"
                "   - Agendamentos -> agendamento-agent\n"
                "   - Produtos/racoes -> consultor-produtos\n"
                "   - Saude/cuidados -> saude-pet\n"
                "4. Se fora do escopo, sugira ligar para a loja\n"
                "5. Ao final, pergunte se pode ajudar em mais alguma coisa\n\n"
                "## Importante\n"
                "- NUNCA invente precos.\n"
                "- Em EMERGENCIA veterinaria: clinica parceira VetLife (11) 98888-0000."
            ),
        },
    )
    resp.raise_for_status()
    project = resp.json()
    print(f"[OK] Projeto criado: {project['id']} - {project['name']}")
    return project["id"]


def create_skills(project_id: str) -> dict[str, str]:
    """Create the 3 RAG skills and return a dict of name -> id."""
    skills_config = [
        {
            "name": "tabela-precos",
            "description": "Tabela de precos de servicos do petshop: banho, tosa, hidratacao, hospedagem",
            "type": "rag",
            "system_prompt": (
                "Use esta base para consultar precos e servicos disponiveis. "
                "Sempre confirme porte do animal antes de informar preco."
            ),
        },
        {
            "name": "catalogo-produtos",
            "description": "Catalogo de racoes, petiscos, brinquedos e acessorios disponiveis na loja",
            "type": "rag",
            "system_prompt": (
                "Use esta base para recomendar produtos. "
                "Sempre pergunte especie, porte e idade do pet antes de recomendar racao."
            ),
        },
        {
            "name": "cuidados-saude",
            "description": "Informacoes sobre cuidados basicos, vacinacao, vermifugacao, sinais de alerta",
            "type": "rag",
            "system_prompt": (
                "Use esta base para orientar sobre cuidados basicos. "
                "NUNCA faca diagnostico veterinario. "
                "Em caso de sintomas graves, sempre oriente a procurar um veterinario."
            ),
        },
    ]

    skill_ids = {}
    for config in skills_config:
        resp = client.post(f"/projects/{project_id}/skills", json=config)
        resp.raise_for_status()
        skill = resp.json()
        skill_ids[config["name"]] = skill["id"]
        print(f"[OK] Skill criada: {skill['id']} - {skill['name']}")

    return skill_ids


def upload_documents(project_id: str) -> None:
    """Upload knowledge base documents for RAG skills.

    Collection names must match those auto-generated by the skills API:
    skill_{name.lower().replace(' ', '_')}
    """
    # Map filename -> skill name (used to derive the correct collection name)
    doc_files = {
        "tabela_precos.txt": "tabela-precos",
        "catalogo_produtos.txt": "catalogo-produtos",
        "cuidados_saude.txt": "cuidados-saude",
    }

    for filename, skill_name in doc_files.items():
        filepath = DATA_DIR / filename
        if not filepath.exists():
            print(f"[SKIP] Arquivo nao encontrado: {filepath}")
            continue

        # Derive collection name the same way the skills API does
        collection = f"skill_{skill_name.lower().replace(' ', '_')}"

        with open(filepath, "rb") as f:
            resp = client.post(
                f"/projects/{project_id}/documents",
                files={"file": (filename, f, "text/plain")},
                data={"collection": collection},
            )
        if resp.status_code < 300:
            doc = resp.json()
            print(f"[OK] Documento enviado: {doc.get('id', '?')} - {filename} -> {collection}")
        else:
            print(f"[WARN] Erro ao enviar {filename}: {resp.status_code} - {resp.text[:200]}")


def create_tools(project_id: str) -> dict[str, str]:
    """Create the 3 API tools and return a dict of name -> id."""
    tools_config = [
        {
            "name": "consultar-agenda",
            "description": "Consulta horarios disponiveis para agendamento de banho, tosa e outros servicos",
            "type": "api",
            "category": "agendamento",
            "api_config": {
                "name": "consultar-agenda",
                "description": (
                    "Retorna horarios disponiveis para agendamento. "
                    "Parametros: data (YYYY-MM-DD), servico (banho|tosa|combo|hospedagem)"
                ),
                "method": "GET",
                "url": "https://api.petshop.com/agenda/disponibilidade",
                "headers": {},
                "auth_type": "none",
                "auth_config": {},
            },
        },
        {
            "name": "criar-agendamento",
            "description": "Cria um agendamento de servico para um pet",
            "type": "api",
            "category": "agendamento",
            "api_config": {
                "name": "criar-agendamento",
                "description": (
                    "Cria agendamento. Body: {cliente_nome, cliente_telefone, "
                    "pet_nome, pet_especie, pet_porte, servico, data, horario}"
                ),
                "method": "POST",
                "url": "https://api.petshop.com/agenda/agendamentos",
                "headers": {"Content-Type": "application/json"},
                "auth_type": "none",
                "auth_config": {},
            },
        },
        {
            "name": "consultar-estoque",
            "description": "Verifica disponibilidade de um produto no estoque da loja",
            "type": "api",
            "category": "produtos",
            "api_config": {
                "name": "consultar-estoque",
                "description": "Consulta estoque de produto. Parametros: produto (nome ou codigo)",
                "method": "GET",
                "url": "https://api.petshop.com/estoque/consulta",
                "headers": {},
                "auth_type": "none",
                "auth_config": {},
            },
        },
    ]

    tool_ids = {}
    for config in tools_config:
        resp = client.post(f"/projects/{project_id}/tools", json=config)
        resp.raise_for_status()
        tool = resp.json()
        tool_ids[config["name"]] = tool["id"]
        print(f"[OK] Tool criada: {tool['id']} - {tool['name']}")

    return tool_ids


def create_agents(project_id: str, skill_ids: dict, tool_ids: dict) -> None:
    """Create the planner + 3 worker agents with linked tools and skills."""

    agents_config = [
        # Planner: Recepcionista Virtual
        {
            "name": "recepcionista",
            "description": "Recepcionista virtual que coordena o atendimento e delega para especialistas",
            "is_planner": True,
            "model": "openai:gpt-4.1-mini",
            "prompt": (
                "Voce e a recepcionista virtual do PetShop Amigo Fiel.\n\n"
                "## Seu papel\n"
                "Voce e o primeiro contato do cliente. Sua funcao e:\n"
                "1. Receber o cliente com simpatia\n"
                "2. Entender o que ele precisa\n"
                "3. Delegar para o sub-agente especializado\n"
                "4. Consolidar a resposta final\n\n"
                "## Regras\n"
                "- Sempre cumprimente com: 'Ola! Bem-vindo ao PetShop Amigo Fiel! "
                "Como posso ajudar voce e seu pet hoje?'\n"
                "- Pergunte o nome do cliente e do pet logo no inicio\n"
                "- Para agendamentos, delegue para 'agendamento-agent'\n"
                "- Para duvidas sobre produtos/racoes, delegue para 'consultor-produtos'\n"
                "- Para duvidas sobre saude/cuidados, delegue para 'saude-pet'\n"
                "- Ao receber a resposta do sub-agente, reformule de forma amigavel\n"
                "- Sempre encerre com: 'Posso ajudar em mais alguma coisa?'\n\n"
                "## Informacoes da Loja\n"
                "- Horario: Seg-Sab 8h-19h, Dom fechado\n"
                "- Endereco: Rua das Flores, 123 - Vila Madalena, SP\n"
                "- WhatsApp: (11) 99999-0000\n"
                "- Pagamento: PIX, cartao, dinheiro"
            ),
            "skill_ids": [
                skill_ids.get("tabela-precos"),
                skill_ids.get("cuidados-saude"),
            ],
            "tool_ids": [],
        },
        # Worker: Agendamento
        {
            "name": "agendamento-agent",
            "description": (
                "Especialista em agendamentos de banho, tosa, hospedagem e outros servicos. "
                "Use para qualquer solicitacao de marcacao, remarcacao ou cancelamento."
            ),
            "is_planner": False,
            "model": "openai:gpt-4.1-mini",
            "prompt": (
                "Voce e o especialista em agendamentos do PetShop Amigo Fiel.\n\n"
                "## Fluxo de Agendamento\n"
                "1. Pergunte qual servico deseja (banho, tosa, combo, hospedagem)\n"
                "2. Pergunte dados do pet: nome, especie, porte, raca\n"
                "3. Pergunte a data desejada\n"
                "4. Use 'consultar-agenda' para verificar disponibilidade\n"
                "5. Apresente horarios disponiveis\n"
                "6. Peca confirmacao: nome do cliente, telefone, dados do pet, servico, data, horario\n"
                "7. Use 'criar-agendamento' para confirmar\n"
                "8. Informe o preco usando a skill de tabela de precos\n\n"
                "## Regras\n"
                "- Se nao houver horario, sugira datas proximas\n"
                "- Para combos (banho+tosa), informe o desconto de 10%\n"
                "- Pacotes mensais: ofereça quando o cliente agendar banho avulso\n"
                "- Hospedagem: pergunte periodo completo (check-in e check-out)\n"
                "- SEMPRE confirme todos os dados antes de criar o agendamento"
            ),
            "tool_ids": [
                tool_ids.get("consultar-agenda"),
                tool_ids.get("criar-agendamento"),
            ],
            "skill_ids": [skill_ids.get("tabela-precos")],
        },
        # Worker: Consultor de Produtos
        {
            "name": "consultor-produtos",
            "description": (
                "Especialista em racoes, petiscos, brinquedos e acessorios. "
                "Use para recomendacoes de produtos, duvidas sobre marcas e consultas de disponibilidade."
            ),
            "is_planner": False,
            "model": "openai:gpt-4.1-mini",
            "prompt": (
                "Voce e o consultor de produtos do PetShop Amigo Fiel.\n\n"
                "## Fluxo de Atendimento\n"
                "1. Pergunte sobre o pet: especie, raca, idade, porte, peso\n"
                "2. Entenda a necessidade: racao, petisco, brinquedo, acessorio\n"
                "3. Para RACOES:\n"
                "   - Pergunte restricoes alimentares ou alergias\n"
                "   - Pergunte preferencia por racao seca ou umida\n"
                "   - Recomende 2-3 opcoes adequadas ao perfil\n"
                "   - Explique diferenciais de cada opcao\n"
                "4. Use 'consultar-estoque' para verificar disponibilidade\n"
                "5. Informe preco e disponibilidade\n\n"
                "## Regras\n"
                "- Priorize racoes premium e super-premium\n"
                "- Para filhotes: racao especifica para filhotes\n"
                "- Para idosos: racao senior\n"
                "- Se nao tiver em estoque, sugira alternativa similar\n"
                "- Nunca force venda - foque em orientacao genuina"
            ),
            "tool_ids": [tool_ids.get("consultar-estoque")],
            "skill_ids": [skill_ids.get("catalogo-produtos")],
        },
        # Worker: Saude Pet
        {
            "name": "saude-pet",
            "description": (
                "Orientador sobre cuidados basicos, vacinacao, vermifugacao, "
                "comportamento animal e quando procurar veterinario. NAO faz diagnosticos."
            ),
            "is_planner": False,
            "model": "openai:gpt-4.1-mini",
            "prompt": (
                "Voce e o orientador de saude e cuidados do PetShop Amigo Fiel.\n\n"
                "## O que voce PODE fazer\n"
                "- Orientar sobre vacinacao (V8/V10 caes, V3/V4/V5 gatos)\n"
                "- Orientar sobre vermifugacao (a cada 3-6 meses)\n"
                "- Orientar sobre antipulgas e carrapatos\n"
                "- Dicas de alimentacao, exercicio e bem-estar\n"
                "- Frequencia ideal de banho por raca\n"
                "- Sinais de alerta para ir ao veterinario\n"
                "- Cuidados com filhotes e idosos\n\n"
                "## O que voce NAO pode fazer\n"
                "- NUNCA faca diagnosticos veterinarios\n"
                "- NUNCA recomende medicamentos\n"
                "- NUNCA minimize sintomas preocupantes\n\n"
                "## Sinais de EMERGENCIA\n"
                "Se o cliente relatar: vomito persistente/com sangue, diarreia com sangue, "
                "dificuldade para respirar, convulsoes, inchaco abdominal, ingestao de toxico, "
                "trauma, ou nao come ha 24h (filhotes 12h):\n\n"
                "Responda: 'Isso pode ser uma emergencia! Leve seu pet IMEDIATAMENTE "
                "ao veterinario. Clinica parceira VetLife: (11) 98888-0000 (24h).'\n\n"
                "## Regras\n"
                "- Use a skill 'cuidados-saude' para embasar orientacoes\n"
                "- Sempre termine com 'Se os sintomas persistirem, consulte um veterinario'\n"
                "- Seja empatico com tutores preocupados"
            ),
            "tool_ids": [],
            "skill_ids": [skill_ids.get("cuidados-saude")],
        },
    ]

    for config in agents_config:
        # Filter out None IDs
        config["tool_ids"] = [tid for tid in config.get("tool_ids", []) if tid]
        config["skill_ids"] = [sid for sid in config.get("skill_ids", []) if sid]

        resp = client.post(f"/projects/{project_id}/agents", json=config)
        resp.raise_for_status()
        agent = resp.json()
        role = "PLANNER" if config["is_planner"] else "WORKER"
        print(f"[OK] Agente criado [{role}]: {agent['id']} - {agent['name']}")


def main():
    print("=" * 60)
    print("  PetShop Amigo Fiel - Setup Automatizado")
    print("=" * 60)
    print(f"\nAPI: {BASE_URL}\n")

    try:
        # Health check - try the base URL without /api/v1
        health_resp = httpx.get(BASE_URL + "/health", timeout=10)
        print(f"[OK] Backend respondendo\n")
    except httpx.ConnectError:
        print(f"[ERRO] Nao foi possivel conectar ao backend em {BASE_URL}")
        print("       Via Docker: docker compose up -d --build")
        print("       Local: uv run uvicorn app.main:app --reload")
        sys.exit(1)

    # 1. Criar projeto
    print("\n--- Criando Projeto ---")
    project_id = create_project()

    # 2. Criar skills
    print("\n--- Criando Skills (Base de Conhecimento) ---")
    skill_ids = create_skills(project_id)

    # 3. Upload documentos
    print("\n--- Enviando Documentos ---")
    upload_documents(project_id)

    # 4. Criar tools
    print("\n--- Criando Tools (APIs) ---")
    tool_ids = create_tools(project_id)

    # 5. Criar agentes
    print("\n--- Criando Agentes ---")
    create_agents(project_id, skill_ids, tool_ids)

    # Resumo
    print("\n" + "=" * 60)
    print("  Setup completo!")
    print("=" * 60)
    print(f"\n  Project ID: {project_id}")
    print(f"  Modo: deep_agent")
    print(f"  Skills: {len(skill_ids)}")
    print(f"  Tools: {len(tool_ids)}")
    print(f"  Agentes: 1 planner + 3 workers")
    print(f"\n  Chat: POST {BASE_URL}/projects/{project_id}/chat")
    print(f"  Stream: POST {BASE_URL}/projects/{project_id}/chat/stream")
    print(f"  Admin UI: http://localhost:8080/projects/{project_id}")
    print()


if __name__ == "__main__":
    main()
